import { NextRequest, NextResponse } from 'next/server'
import { jsPDF } from 'jspdf'
import { createClient } from '@/lib/supabase/server'
import { publicTenderBySlug } from '@/lib/tenders'
import { formatCurrency, formatDate } from '@/lib/utils'

/**
 * Converts Khmer numerals to standard Arabic digits (0-9)
 */
function convertKhmerNumerals(str: string): string {
  return str.replace(/[០-៩]/g, (d) => String(d.charCodeAt(0) - 0x17E0))
}

/**
 * Sanitizes and Romanizes text for jsPDF standard ASCII/Latin-1 (WinAnsi) font encoding.
 * Translates/cleans Khmer script boilerplate to prevent mojibake glyph corruption.
 */
function cleanTextForPdf(text: string | null | undefined, fallback: string = ''): string {
  if (!text) return fallback

  let cleaned = text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/[\u2026]/g, '...')
    .replace(/[\u00A0]/g, ' ')

  cleaned = convertKhmerNumerals(cleaned)

  // If text contains Khmer Unicode range (\u1780-\u17FF)
  if (/[\u1780-\u17FF]/.test(cleaned)) {
    const annMatch = cleaned.match(/លេខ\s*([0-9\.\s]+)\s*([A-Za-z\.]+)?/)
    const annNum = annMatch
      ? `Announcement No. ${annMatch[1].replace(/\s+/g, '')}${annMatch[2] ? ' ' + annMatch[2] : ''}`
      : ''

    let englishPortion = cleaned
      .replace(/[\u1780-\u17FF\u17D2\u17D7\u17D9\u17DA\u17B4-\u17D3]+/g, ' ')
      .replace(/[0-9]+\s*PC\.[A-Za-z\.]*/gi, ' ')
      .replace(/\(\s*[\d\.\,\s]*\)/g, ' ')
      .replace(/\s*[\,\.\-]+\s*[\,\.\-]+/g, ' ')
      .replace(/\s+/g, ' ')
      .replace(/^\s*[\.\,\-\:\_]+\s*/, '')
      .trim()

    if (englishPortion.length > 5) {
      cleaned = annNum ? `${annNum} — ${englishPortion}` : englishPortion
    } else if (annNum) {
      cleaned = `${annNum} — procurement notice (translated from Khmer original)`
    } else {
      cleaned = fallback || 'Procurement notice (translated from Khmer original)'
    }
  }

  // Strip any remaining non-ASCII characters that cannot be rendered by standard jsPDF fonts
  cleaned = cleaned.replace(/[^\x20-\x7E\n\r\t]/g, ' ').replace(/\s+/g, ' ').trim()

  return cleaned || fallback
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params

  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    return NextResponse.json({ error: 'Supabase configuration missing' }, { status: 500 })
  }

  try {
    const supabase = await createClient()
    const { data: tender, error } = await publicTenderBySlug(supabase, slug).maybeSingle()

    if (error || !tender) {
      return NextResponse.json({ error: 'Tender notice not found or unapproved' }, { status: 404 })
    }

    const rawOrgName = (tender.organizations as any)?.name_en || (tender.organizations as any)?.name_km || ''
    const rawCatName = (tender.categories as any)?.name_en || ''
    const rawSrcName = (tender.sources as any)?.name || ''

    const orgName = cleanTextForPdf(rawOrgName, 'Procuring entity not recorded')
    const catName = cleanTextForPdf(rawCatName, 'Not recorded')
    const srcName = cleanTextForPdf(rawSrcName, 'Not recorded')
    const refNumber = cleanTextForPdf(tender.reference_number || tender.external_id, 'N/A')
    const budgetStr = formatCurrency(tender.estimated_value, tender.currency || 'USD')
    const deadlineStr = tender.deadline ? formatDate(tender.deadline) : 'Not stated in notice'
    const pubStr = tender.published_at ? formatDate(tender.published_at) : 'Not recorded'
    const cleanTitle = cleanTextForPdf(tender.title, 'Tender Notice')
    const cleanSummary = cleanTextForPdf(tender.summary || tender.description, '')
    const procMethod = cleanTextForPdf(tender.procurement_method, '')

    const parseList = (val: any): string[] =>
      Array.isArray(val) ? val : (typeof val === 'string' ? JSON.parse(val || '[]') : [])

    const products = parseList(tender.products_services).map((p) => cleanTextForPdf(p)).filter(Boolean)
    const requirements = parseList(tender.requirements).map((r) => cleanTextForPdf(r)).filter(Boolean)

    // Generate Standard Bidding Document PDF using jsPDF
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    let y = 18

    // --- HEADER: Brand Accent ---
    doc.setFillColor(37, 99, 235) // Blue-600 top brand accent
    doc.rect(0, 0, pageWidth, 5, 'F')

    // Document Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(15, 23, 42) // Slate-900
    doc.text('TENDER SUMMARY SHEET', pageWidth / 2, y, { align: 'center' })
    y += 5.5

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(100, 116, 139) // Slate-500
    doc.text('Auto-generated by BidHubKH from public notice data — NOT an official document', pageWidth / 2, y, { align: 'center' })
    y += 7

    doc.setDrawColor(226, 232, 240) // Slate-200 divider
    doc.setLineWidth(0.4)
    doc.line(14, y, pageWidth - 14, y)
    y += 6

    // --- PROCURING ENTITY & TENDER TITLE ---
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9.5)
    doc.setTextColor(37, 99, 235) // Blue-600
    doc.text(orgName.toUpperCase(), 14, y)
    y += 5

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(15, 23, 42)
    const splitTitle = doc.splitTextToSize(cleanTitle, pageWidth - 28)
    doc.text(splitTitle, 14, y)
    y += splitTitle.length * 4.8 + 4

    // --- METADATA HIGHLIGHT GRID BOX (Non-overlapping 2-column layout) ---
    const boxHeight = 36
    doc.setFillColor(248, 250, 252) // Slate-50 background
    doc.setDrawColor(203, 213, 225) // Slate-300 border
    doc.roundedRect(14, y, pageWidth - 28, boxHeight, 2, 2, 'FD')

    const col1X = 18
    const col2X = 104
    const colWidth = 82

    const metaRows = [
      { label1: 'PROCUREMENT REFERENCE:', val1: refNumber, label2: 'ESTIMATED BUDGET:', val2: budgetStr },
      { label1: 'SUBMISSION DEADLINE:', val1: deadlineStr, label2: 'PROCUREMENT METHOD:', val2: procMethod || 'Not stated in notice' },
      { label1: 'SECTOR CATEGORY:', val1: catName, label2: 'SOURCE PORTAL:', val2: srcName }
    ]

    metaRows.forEach((row, i) => {
      const rowY = y + 5.5 + i * 11
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7.5)
      doc.setTextColor(100, 116, 139)
      doc.text(row.label1, col1X, rowY)
      doc.text(row.label2, col2X, rowY)

      doc.setFontSize(8.5)
      doc.setTextColor(15, 23, 42)
      doc.text(doc.splitTextToSize(row.val1, colWidth)[0] || row.val1, col1X, rowY + 4)
      doc.text(doc.splitTextToSize(row.val2, colWidth)[0] || row.val2, col2X, rowY + 4)
    })

    y += boxHeight + 6

    // --- SECTION 1: EXECUTIVE SUMMARY & OBJECTIVE ---
    if (cleanSummary) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9.5)
      doc.setTextColor(30, 41, 59)
      doc.text('1. SUMMARY FROM ORIGINAL NOTICE', 14, y)
      y += 4.5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(51, 65, 85)
      const splitSummary = doc.splitTextToSize(cleanSummary, pageWidth - 28)
      doc.text(splitSummary, 14, y)
      y += splitSummary.length * 4.2 + 4
    }

    // --- SECTION 2: PRODUCTS, TECHNICAL SPECIFICATIONS & SCOPE ---
    if (products.length > 0) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9.5)
      doc.setTextColor(30, 41, 59)
      doc.text('2. TECHNICAL SPECIFICATIONS & SCOPE OF SUPPLY', 14, y)
      y += 4.5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(51, 65, 85)

      products.slice(0, 8).forEach((item) => {
        doc.setFillColor(37, 99, 235) // Blue bullet point
        doc.circle(16.5, y - 1, 0.7, 'F')
        const splitItem = doc.splitTextToSize(item, pageWidth - 34)
        doc.text(splitItem, 19, y)
        y += splitItem.length * 3.8 + 1.2
      })
      y += 3
    }

    // --- SECTION 3: MANDATORY ELIGIBILITY & COMPLIANCE RULES ---
    if (requirements.length > 0 || tender.eligibility) {
      if (y > 225) {
        doc.addPage()
        y = 20
      }

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9.5)
      doc.setTextColor(30, 41, 59)
      doc.text('3. MANDATORY ELIGIBILITY & COMPLIANCE REQUIREMENTS', 14, y)
      y += 4.5

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(51, 65, 85)

      if (tender.eligibility) {
        const cleanElig = cleanTextForPdf(tender.eligibility)
        const splitElig = doc.splitTextToSize(cleanElig, pageWidth - 28)
        doc.text(splitElig, 14, y)
        y += splitElig.length * 3.8 + 2
      }

      requirements.slice(0, 6).forEach((req) => {
        doc.setFillColor(16, 185, 129) // Emerald bullet point
        doc.circle(16.5, y - 1, 0.7, 'F')
        const splitReq = doc.splitTextToSize(req, pageWidth - 34)
        doc.text(splitReq, 19, y)
        y += splitReq.length * 3.8 + 1.2
      })
      y += 3
    }

    // --- SECTION 4: SOURCE & EXTRACTION NOTES ---
    if (y > 235) {
      doc.addPage()
      y = 20
    }

    doc.setFillColor(241, 245, 249) // Slate-100
    doc.roundedRect(14, y, pageWidth - 28, 22, 2, 2, 'F')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(15, 23, 42)
    doc.text('SOURCE & EXTRACTION NOTES', 18, y + 5)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.2)
    doc.setTextColor(71, 85, 105)
    const confNote = typeof tender.confidence_score === 'number'
      ? ` • AI extraction estimate: ${tender.confidence_score}%`
      : ''
    doc.text(`Notice Published: ${pubStr}${confNote}. This sheet is a BidHubKH-generated summary, not an authority-issued document.`, 18, y + 9.5)
    if (tender.original_url) {
      const portalUrl = tender.original_url
      doc.text(`Original notice: ${portalUrl.length > 92 ? portalUrl.slice(0, 89) + '...' : portalUrl}`, 18, y + 14)
    } else {
      doc.text('Original notice: link not captured — refer to the issuing authority\'s website.', 18, y + 14)
    }
    doc.text('For formal bid envelope submission and inquiries, always use the issuing authority\'s official channels.', 18, y + 18)

    // --- FOOTER ---
    doc.setFontSize(7)
    doc.setTextColor(148, 163, 184)
    doc.text('BidHubKH — Cambodian Tender Intelligence Platform • www.bidhubkh.com', pageWidth / 2, 290, { align: 'center' })

    const pdfOutput = doc.output('arraybuffer')
    const filename = `${tender.slug || 'tender'}-tender-summary.pdf`

    return new Response(pdfOutput, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'public, max-age=3600'
      }
    })
  } catch (err: any) {
    console.error('PDF Generation Error:', err)
    return NextResponse.json({ error: 'Failed to generate tender summary PDF' }, { status: 500 })
  }
}
