-- 00011: Honest tender_document records.
--
-- Migration 00008 seeded tender_documents whose names claimed to be authority-issued
-- artifacts ("Standard Bidding Document (SBD) — …", "Terms of Reference (TOR) — …") with
-- fabricated file_size_bytes, while original_url pointed back at BidHubKH's own summary
-- generator (/api/tenders/{slug}/pdf). The web UI and PDF route now label these honestly
-- as auto-generated summary sheets; this migration corrects the stored records to match.
--
-- Scope guard: only rows served by the generator are touched (original_url starts with
-- '/api/tenders/'), so genuinely scraped documents are unaffected.

UPDATE public.tender_documents
SET name = 'Tender Summary Sheet (auto-generated by BidHubKH)',
    document_type = 'summary_sheet',
    file_size_bytes = NULL
WHERE original_url LIKE '/api/tenders/%';
